apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-demo.fullname" . }}
  namespace: helm-practice
  labels:
    {{- include "spring-demo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spring-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spring-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP