apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-demo.fullname" . }}
  labels:
    {{- include "spring-demo.labels" . | nindent 4 }}
  namespace: helm-practice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "spring-demo.selectorLabels" . | nindent 4 }}
