on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kktest1.azurecr.io
        username: ${{ secrets.acr_kktest1_username }}
        password: ${{ secrets.acr_kktest1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kktest1.azurecr.io/kubetest:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push kktest1.azurecr.io/kubetest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubetest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kube-testaecc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kube-testaecc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kube-testaecc
        container-registry-url: kktest1.azurecr.io
        container-registry-username: ${{ secrets.acr_kktest1_username }}
        container-registry-password: ${{ secrets.acr_kktest1_password }}
        secret-name: kubetestdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: spring-demo
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:kktest1.azurecr.io/kubetest
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:kubetestdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kube-testaecc
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          kktest1.azurecr.io/kubetest:${{ github.sha }}
        imagepullsecrets: |
          kubetestdockerauth
